export type AssessmentMenuTabValueType =
  | 'ASSESSMENT1'
  | 'ASSESSMENT2'
  | 'ASSESSMENT3'
  | 'ASSESSMENT4'
  | 'ASSESSMENT5'
  | 'ASSESSMENT61'
  | 'ASSESSMENT612'
  | 'ASSESSMENT62'
  | 'ASSESSMENT634'
  | 'ASSESSMENT65'
  | 'ASSESSMENT66'
  | 'ASSESSMENT7'
  | 'SCHEDULE';
